### ISSUE TITLE
CluserMemoryStoreWorker: process.send() returned false indicating that the channel is closed and/or there is a large backlog of messages waiting to be sent.

### ISSUE THREAD

**Issue by sefinek** [express-rate-limit/cluster-memory-store#2]
How can i fix this error?

```
11|cdn       | 20:34:40.235 07.11.2023: Error: CluserMemoryStoreWorker: process.send() returned false indicating that the channel is closed and/or there is a large backlog of messages waiting to be sent.
11|cdn       |     at /home/sefek/node/www/cdn.sefinek.net/node_modules/@express-rate-limit/cluster-memory-store/dist/index.cjs:150:11
11|cdn       |     at new Promise (<anonymous>)
11|cdn       |     at ClusterMemoryStoreWorker.send (/home/node/www/cdn.sefinek.net/node_modules/@express-rate-limit/cluster-memory-store/dist/index.cjs:109:12)
11|cdn       |     at ClusterMemoryStoreWorker.increment (/home/node/www/cdn.sefinek.net/node_modules/@express-rate-limit/cluster-memory-store/dist/index.cjs:83:49)
11|cdn       |     at /home/node/www/cdn.sefinek.net/node_modules/express-rate-limit/dist/index.cjs:630:59
11|cdn       |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
11|cdn       |     at async /home/node/www/cdn.sefinek.net/node_modules/express-rate-limit/dist/index.cjs:611:5
11|cdn       | 20:34:41.240 07.11.2023: Error: ClusterMemoryStoreWorker: no response recieved to increment command after 1000ms.
11|cdn       |     at Timeout._onTimeout (/home/node/www/cdn.sefinek.net/node_modules/@express-rate-limit/cluster-memory-store/dist/index.cjs:114:11)
11|cdn       |     at listOnTimeout (node:internal/timers:573:17)
11|cdn       |     at process.processTimers (node:internal/timers:514:7)
```

### index.js
```js
const cluster = require('node:cluster');
const { availableParallelism } = require('node:os');
const { ClusterMemoryStorePrimary } = require('@express-rate-limit/cluster-memory-store');

if (cluster.isMaster) {
	console.log(`Primary ${process.pid} is running`);

	const rateLimiterStore = new ClusterMemoryStorePrimary();
	rateLimiterStore.init();

	const numberCPUs = availableParallelism();
	for (let i = 0; i < numberCPUs; i++) {
		cluster.fork();
	}

	cluster.on('exit', (worker, code, signal) => {
		console.log(`Worker ${worker.process.pid} died with code ${code} from signal ${signal}.`);
	});
} else {
	require('./server.js');

	console.log(`Worker ${process.pid} started`);
}
```

### ratelimit.js
```js
const rateLimit = require('express-rate-limit');
const { ClusterMemoryStoreWorker } = require('@express-rate-limit/cluster-memory-store');
const { rateLimited } = require('../middlewares/other/errors.js');

const limiter = rateLimit({
	store: new ClusterMemoryStoreWorker(),

	windowMs: 5 * 60 * 1000,
	limit: 500,
	standardHeaders: 'draft-7',
	legacyHeaders: false,

	skip: req => req.ip === '::ffff:127.0.0.1',

	handler: rateLimited,
});

module.exports = limiter;
```

I use PM2

**Comment by nfriedly** [comment]
Hum, your code looks right to me. I haven't worked with PM2 much, what is the command you run to start the server?

**Comment by nfriedly** [comment]
After looking at the PM2 docs a bit, I'm guessing you're using [cluster mode](https://pm2.keymetrics.io/docs/usage/cluster-mode/) with something like `pm2 start server.js -i max`, which means it doesn't actually run your `index.js` - instead PM2 runs it's own Primary that doesn't have the ClusterMemoryStore set up.

If that's the case, then I can think of a couple of options:
* Don't use PM2's built-in clustering, instead run `pm2 start index.js` and then let your code manage the clustering
* Use an external store, such as [Redis](https://www.npmjs.com/package/rate-limit-redis) or [Memcached](https://www.npmjs.com/package/rate-limit-memcached), that doesn't depend on running code in the cluster Primary

There's also a [message exchange feature request open on PM2](https://github.com/Unitech/pm2/issues/5295) - if that were implimented, then the ClusterMemoryStore could possibly be updated to use it.

**Comment by nfriedly** [comment]
Actually, it looks like there might be a third option using the [PM2 API](https://pm2.keymetrics.io/docs/usage/pm2-api/). I'll have to look at it a bit more when I have more time.

**Comment by sefinek** [comment]
> Hum, your code looks right to me. I haven't worked with PM2 much, what is the command you run to start the server?

Just `pm2 start`. It loads the `ecosystem config`.
### ecosystem.config.js
```js
module.exports = {
        apps: [{
                name                  : 'cdn',
                script                : './index.js',

                log_date_format       : 'HH:mm:ss.SSS DD.MM.YYYY',
                merge_logs            : true,
                log_file                      : '/home/sefinek/logs/www/cdn.sefinek.net/combined.log',
                out_file              : '/home/sefinek/logs/www/cdn.sefinek.net/out.log',
                error_file            : '/home/sefinek/logs/www/cdn.sefinek.net/error.log',

                max_restarts          : 8,
                restart_delay         : 6000,
                wait_ready            : true,

                instances             : 'max',
                exec_mode             : 'cluster',
        }],
};
```


> After looking at the PM2 docs a bit, I'm guessing you're using cluster mode with something like pm2 start server.js -i max, which means it doesn't actually run your index.js - instead PM2 runs it's own Primary that doesn't have the ClusterMemoryStore set up.

And yes, I'm using cluster mode. It then looks like this: ![img](https://cdn.sefinek.net/static/07.11.2023/WindowsTerminal_eweYTB0xVDug.png)

After starting:
```
8|cdn | 23:08:03.271 07.11.2023: Worker 124282 started
8|cdn | 23:08:03.291 07.11.2023: Worker 124283 started
8|cdn | 23:08:04.123 07.11.2023: Worker 124314 started
8|cdn | 23:08:04.145 07.11.2023: Worker 124315 started
```

Indeed, `primary` is never being launched.

**Comment by nfriedly** [comment]
Oh, I get it, it is using the index.js, but only in the worker threads, so that `cluster.isMaster` is never true. 

Try this config:

```
                instances             : 1,
                exec_mode             : 'fork',
```

I think that will let your code take over responsibility from PM2 for managing the cluster.

**Comment by sefinek** [comment]
I changed exec_mode to `fork` a few days ago but without `cluster-memory-store` and it still works normal (with the  `primary` worker). ill check this module later. thank you for your response

**Comment by sefinek** [comment]
Idk why but it doesnt work with my Routes

https://github.com/express-rate-limit/cluster-memory-store/assets/92880265/1de77866-479a-4bcf-9f66-df273f80c5b2

**Comment by nfriedly** [comment]
Ok, I'm going to try and add some debug logging to see if I can get a better understanding of what's going on.

In the meanwhile, I noticed that you have a MongoDB, so you might have better luck with https://www.npmjs.com/package/rate-limit-mongo instead of cluster-memory-store.

**Comment by nfriedly** [comment]
Alright, try the debug branch:

`npm install "https://github.com/express-rate-limit/cluster-memory-store#debug"`

and then launch it with `DEBUG=* node .` to get a whole lot of debug logs, or `DEBUG=cluster-memory-store:* node .` to filter it down to only the ones I just added.

**Comment by sefinek** [comment]
@nfriedly, I sent you those logs to your email address because some of them contained sensitive information that shouldn't be shared publicly here (:

**Comment by nfriedly** [comment]
Sorry, I was out last week and I'm just now getting to look at this again. 

I think that part of the problem is that the initialization process is just taking more than 1 second, and then the timeout is loggin an error, and then after another second or two, it completes. 

Aside from that error, it appears to be working correctly (?)

So, I think I should bump up the initialization timeout, 10 seconds ought to be enough. I think I should probably also stick the worker ID in any error messages that a worker logs.

**Comment by nfriedly** [comment]
Ok, I updated the `debug` branch with both of those changes. I think the [same commands as before](https://github.com/express-rate-limit/cluster-memory-store/issues/2#issuecomment-1813792245) will update your local copy; can you try it out again?

**Comment by sefinek** [comment]
Checked, it works fine on my computer. Let's see how it performs on production.

```js
// Middlewares
app.use(helmet({ crossOriginResourcePolicy: false, contentSecurityPolicy: false }));
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ limit: '1mb', extended: true }));
app.use(timeout());
app.use(express.static('public'));
app.use(limiter);
app.use(favicon(__dirname + '/public/favicon.png'));
app.use(logger);
app.use(cookieParser());
```

```js
const rateLimit = require('express-rate-limit');
const { ClusterMemoryStoreWorker } = require('@express-rate-limit/cluster-memory-store');
const RenderError = require('./renderError.js');

const limiter = rateLimit({
	store: process.env.NODE_ENV === 'production' ? new ClusterMemoryStoreWorker() : null,

	windowMs: 3 * 60 * 1000,
	limit: 35,
	standardHeaders: 'draft-7',
	legacyHeaders: false,

	skip: req => req.ip === '::ffff:127.0.0.1',

	handler: (req, res) => RenderError(req, res, 429),
});

module.exports = limiter;
```

**Comment by sefinek** [comment]
Tested and works fine ✔

**Comment by nfriedly** [comment]
Great! I'll go ahead and ship the change

**Comment by nfriedly** [comment]
Ok, it's now live on npm as v0.2.0
